import { Temple } from './types';

export const TEMPLES_DATA: Temple[] = [
  {
    id: "tirupati",
    name: "Tirumala Venkateswara Temple",
    originalName: "తిరుమల శ్రీ వేంకటేశ్వర ఈ ఆలయం",
    deity: "Lord Venkateswara (Balaji)",
    state: "Andhra Pradesh",
    city: "Tirupati",
    district: "Chittoor",
    rating: 4.9,
    isPopular: true,
    description: "Perched atop the seven hills of Seshachalam, Tirumala Venkateswara Temple is the most visited, wealthiest, and spiritually radiant temple in the world. Revered as Kaliyuga Vaikuntam, this historical shrine represents pristine Dravidian architecture and eternal spiritual energy.",
    history: "Dating back to the 5th century CE, the temple received immense patronage from Pallavas, Cholas, Pandyas, and grand kings of the Vijayanagara Empire like Sri Krishnadevaraya. The deity Lord Venkateswara is self-manifested (Swayambhu) and stands as a beacon of salvation and divine refuge in the current cosmic age.",
    established: "5th Century CE",
    architecture: "Ancient Dravidian Heritage",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    location: { lat: 13.6833, lng: 79.3500 },
    timings: {
      opening: "03:00 AM",
      closing: "11:30 PM",
      morningDarshan: "06:00 AM - 12:00 PM",
      eveningDarshan: "01:00 PM - 10:00 PM",
      specialDarshan: "05:00 AM - 09:00 PM (Quick Darshan / Seeghra Darshan)"
    },
    dressCode: {
      men: "Dhoti with Kurta/Angavastram, or formal traditional trousers and shirt. Strictly no shorts, t-shirts, trackpants, or western nightwear.",
      women: "Saree, Half-saree, or traditional Chudidar with Dupatta. Leggings, jeans, short tops, or sleeveless wear are strictly prohibited.",
      restricted: "Jeans, ripped items, hats, sunglasses, shorts, or leather accessories inside the main temple parameter."
    },
    facilities: {
      parking: true,
      restrooms: true,
      water: true,
      wheelchair: true,
      lockers: true,
      accommodation: true,
      medical: true
    },
    food: {
      annadanamStatus: 'Available',
      annadanamTimings: "09:00 AM to 11:00 PM (Continuous distribution)",
      breakfast: "09:00 AM - 11:30 AM (Upma, Pongal, Milk)",
      lunch: "12:00 PM - 04:00 PM (Traditional South Indian meals, curd, sweet payasam)",
      dinner: "06:30 PM - 11:00 PM (Rice, sambar, buttermilk, pickle)",
      capacity: 5000,
      diningHallLocation: "Matrusri Tarigonda Vengamamba Annaprasadam Complex, North Mada Street",
      prasadamList: [
        { name: "Srivari Laddu (Large)", type: "Laddu", price: 50, free: false, collectionPoint: "Srivari Laddu Counters" },
        { name: "Pulihora (Tamarind Rice)", type: "Rice", price: 0, free: true, collectionPoint: "Vaikuntam Queue Complex" },
        { name: "Chakkara Pongal (Sweet)", type: "Dessert", price: 0, free: true, collectionPoint: "Darshan Exit Gates" },
        { name: "Daddojanam (Curd Rice)", type: "Rice", price: 20, free: false, collectionPoint: "Prasadam Sales Stall" }
      ]
    },
    contact: {
      phone: "+91-8772277777",
      website: "https://tirupatibalaji.ap.gov.in",
      email: "helpdesk@ttdtemples.ap.gov.in"
    },
    timeline: [
      { time: "03:00 AM", event: "Suprabhata Seva (Wake-up chant)", type: "seva" },
      { time: "03:30 AM", event: "Thomala Seva & Archana", type: "seva" },
      { time: "04:30 AM", event: "Srivari Koluvu & Panchanga Sravanam", type: "seva" },
      { time: "06:00 AM", event: "Sarvadarsanam (General Darshan Starts)", type: "darshan" },
      { time: "09:00 AM", event: "Morning Food distribution & Annadanam Breakfast", type: "food" },
      { time: "12:00 PM", event: "Sri Tarigonda Vengamamba Annadanam Lunch begins", type: "food" },
      { time: "05:00 PM", event: "Sahasra Deepalankarana Seva (Outer Procession)", type: "seva" },
      { time: "06:30 PM", event: "Annadanam Dinner Starts", type: "food" },
      { time: "10:30 PM", event: "Ekanta Seva (Deity Resting Ceremony)", type: "seva" },
      { time: "11:30 PM", event: "Temple Main Gates Closed", type: "general" }
    ],
    crowdLevel: 'High',
    crowdTrend: [
      { hour: "04:00 AM", count: 85, text: "Extremely Busy - Suprabhatam crowd" },
      { hour: "08:00 AM", count: 95, text: "Peak rush - General queue is high" },
      { hour: "12:00 PM", count: 70, text: "Moderate flow - Lunch transition list" },
      { hour: "04:00 PM", count: 65, text: "Slight relief before evening sevas" },
      { hour: "08:00 PM", count: 90, text: "Evening rush - High wait times" }
    ],
    weather: {
      temp: 34,
      text: "Sunny & Cozy",
      forecast: "Expect hot morning hours, pleasant breeze after 06:00 PM",
      warning: "Highly humid. Stay hydrated while standing in walk-queue corridors."
    },
    festivals: [
      { name: "Srivari Brahmotsavam", date: "September 15, 2026", countdown: "95 Days", description: "The majestic 9-day annual chariot vehicle festival which witnesses divine representations and grand processions under the oversight of Lord Brahma." },
      { name: "Vaikunta Ekadasi", date: "December 21, 2026", countdown: "192 Days", description: "The supreme auspicious day when the doors of inner Vaikuntam (Vaikunta Dwaram) are unlocked for visual and physical purification." }
    ],
    nearbyServices: [
      { name: "Srinivasam Guest House", type: "Hotel", rating: 4.2, distance: "1.2 km", address: "Opposite RTC Bus Stand, Tirupati Urban" },
      { name: "Bhimas Deluxe Vegetarian Cafe", type: "Restaurant", rating: 4.6, distance: "0.8 km", address: "G-Car Street, Tirupati Outer" },
      { name: "TTD Central Hospital", type: "Hospital", rating: 4.4, distance: "2.1 km", address: "Bypass junction Road, Tirupati" },
      { name: "State Bank of India 24x7 ATM", type: "ATM", rating: 4.0, distance: "0.2 km", address: "Near Devasthanam Toll Plaza" }
    ],
    liveStreamUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ" // Standard simulated stream URL
  },
  {
    id: "kashi",
    name: "Kashi Vishwanath Temple",
    originalName: "काशी विश्वनाथ मंदिर",
    deity: "Lord Shiva (Vishwanatha)",
    state: "Uttar Pradesh",
    city: "Varanasi",
    district: "Varanasi",
    rating: 4.8,
    isPopular: true,
    description: "Located on the sacred western bank of the holy Ganges river in Varanasi, Kashi Vishwanath contains the venerated Jyotirlinga, the golden spire of spiritual axis representing the cosmic light of Shiva. It represents liberation (Moksha) and timeless continuous prayers.",
    history: "References to this eternal shrine are found in Puranic texts like Upanishads and Skanda Purana. Despite historic interventions, the modern divine shrine was beautifully commissioned and reconstructed by the legendary Queen of Malwa, Maharani Ahilyabai Holkar in 1780. The iconic gold spire was gifted by Maharaja Ranjit Singh.",
    established: "Traditional Origin / Ahilyabai Holkar (1780)",
    architecture: "Nagara & Kashi Shastric Temple style",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0db?auto=format&fit=crop&w=1200&q=80",
    location: { lat: 25.3109, lng: 83.0104 },
    timings: {
      opening: "02:30 AM",
      closing: "11:00 PM",
      morningDarshan: "06:00 AM - 11:30 AM",
      eveningDarshan: "01:00 PM - 09:30 PM",
      specialDarshan: "04:00 AM - 05:30 AM (Sugam Darshan ticket holders)"
    },
    dressCode: {
      men: "Kurta-pyjama or Dhoti with Angavastram. Strictly no shorts, lungis, singlets, or casual beachwear permitted near the inner sanctum.",
      women: "Saree, Salwar Suit, or traditional Indian clothing with dupatta. Avoid revealing shoulders, short pants, or leather jackets.",
      restricted: "Western skirts, tight leggings without overskirts, smartwatches, or metallic items during sanctum entry."
    },
    facilities: {
      parking: false,
      restrooms: true,
      water: true,
      wheelchair: true,
      lockers: true,
      accommodation: false,
      medical: true
    },
    food: {
      annadanamStatus: 'Available',
      annadanamTimings: "11:30 AM to 03:00 PM daily",
      breakfast: "No regular breakfast distributed; free morning hot herbal milk during extreme winter days",
      lunch: "11:30 AM - 03:00 PM (Kashi special Satvik Thali: rice, urad dal, aloo dum, puri, kheer)",
      dinner: "No dinner (Only occasional festival prasad hand-outs)",
      capacity: 2500,
      diningHallLocation: "Shri Kashi Vishwanath Annapurna Rasoi, near Neelkanth Lane",
      prasadamList: [
        { name: "Peda Prasad", type: "Dessert", price: 60, free: false, collectionPoint: "Vishwanath Corridor Counters" },
        { name: "Sattu & Dry Fruits mixture", type: "Snack", price: 40, free: false, collectionPoint: "Corridor Exit Counter" },
        { name: "Ganga Jal (Holy Ganges Water)", type: "Water", price: 0, free: true, collectionPoint: "Mandir Entry Point" }
      ]
    },
    contact: {
      phone: "+91-5422392629",
      website: "https://shrikashivishwanath.org",
      email: "info@shrikashivishwanath.org"
    },
    timeline: [
      { time: "02:30 AM", event: "Main Gates open & Mangala Aarti preparation", type: "seva" },
      { time: "03:00 AM", event: "Mangala Aarti (Highly powerful morning prayers)", type: "seva" },
      { time: "04:00 AM", event: "Sugam Darshan & General Darshan begins", type: "darshan" },
      { time: "11:15 AM", event: "Bhog Aarti & Traditional mid-day offerings", type: "seva" },
      { time: "11:30 AM", event: "Shree Annapurna Bhojan Lunch starts", type: "food" },
      { time: "07:00 PM", event: "Sapta Rishi Aarti (Holy recitation by seven priests)", type: "seva" },
      { time: "09:00 PM", event: "Shringar Aarti (Decoration flowers display)", type: "seva" },
      { time: "10:30 PM", event: "Shayan Aarti (Night rest lullaby)", type: "seva" },
      { time: "11:00 PM", event: "Mandir Gates Closed", type: "general" }
    ],
    crowdLevel: 'Medium',
    crowdTrend: [
      { hour: "03:00 AM", count: 75, text: "Busy - Mangala Aarti rush" },
      { hour: "08:00 AM", count: 60, text: "Moderate queue - Morning bathing crowd" },
      { hour: "12:00 PM", count: 45, text: "Manageable crowd during Bhog Aarti" },
      { hour: "06:00 PM", count: 85, text: "Extremely Busy - Sapta Rishi evening queue" },
      { hour: "09:00 PM", count: 50, text: "Calm before Shayan Seva" }
    ],
    weather: {
      temp: 36,
      text: "Warm & Clear",
      forecast: "High heat index during afternoon. Cool breeze near Ganga ghat steps.",
      warning: "Wear comfortable cotton footwear. Stone tiles can get very hot during mid-day."
    },
    festivals: [
      { name: "Maha Shivaratri", date: "March 8, 2026", countdown: "Passed", description: "The grandest cosmic union night of Shiva and Parvati, drawing over 500,000 pilgrims for holy abhishekam." },
      { name: "Dev Deepawali", date: "November 23, 2026", countdown: "164 Days", description: "The divine spectacular night of gods when all Ghats of Kashi are lit with 1.2 million clay lamps, radiating celestial power." }
    ],
    nearbyServices: [
      { name: "Alka Guest House", type: "Hotel", rating: 4.5, distance: "0.2 km", address: "Dashashwamedh Ghat road, Varanasi" },
      { name: "Keshari Indian Satvik Restaurant", type: "Restaurant", rating: 4.7, distance: "0.4 km", address: "Near Vishwanath lane corner" },
      { name: "Apex Trauma Hospital Varanasi", type: "Hospital", rating: 4.3, distance: "3.5 km", address: "Lanka road, Varanasi" },
      { name: "HDFC Bank Safe ATM", type: "ATM", rating: 4.1, distance: "0.1 km", address: "Madanpura crossing, Banaras" }
    ],
    liveStreamUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "kedarnath",
    name: "Kedarnath Temple",
    originalName: "श्री केदारनाथ ज्योतिर्लिंग",
    deity: "Lord Shiva (Sadashiva)",
    state: "Uttarakhand",
    city: "Kedarnath Valley",
    district: "Rudraprayag",
    rating: 4.9,
    isPopular: true,
    description: "Nestled in the majestic snow-clad Garhwal Himalayas at 3,583 meters above sea level near Mandakini river, Kedarnath represents the highest of 12 Jyotirlingas, representing eternal absolute presence of Lord Shiva as Pandavas' divine redeemer.",
    history: "Originally constructed of solid hand-hewn granite slabs by the legendary Pandava brothers to seek absolute penance and grace from Shiva, the shrine was revived and beautifully rebuilt by Adi Shankaracharya during the 8th Century. It stood unaffected through multiple glacier epochs.",
    established: "8th Century (Restored)",
    architecture: "Himalayan Stone Architecture",
    image: "https://images.unsplash.com/photo-1614093867025-a1c1d0bcdc99?auto=format&fit=crop&w=1200&q=80",
    location: { lat: 30.7352, lng: 79.0669 },
    timings: {
      opening: "04:00 AM",
      closing: "09:00 PM (Temple closes during peak winter months)",
      morningDarshan: "06:00 AM - 03:00 PM",
      eveningDarshan: "05:00 PM - 08:30 PM",
      specialDarshan: "04:30 AM - 06:00 AM (Special Abhishekam Darshan)"
    },
    dressCode: {
      men: "Warm woolens, thermal jackets, trousers, or traditional wool-suits. Avoid thin linen fabrics since temperature easily drops below freezing.",
      women: "Warm traditional suits, windproof jackets, shawls, and heavy boots. High-heeled or slippery shoes are highly unsafe.",
      restricted: "Short trousers, uncovered shoulders, expensive leather goods, or plastic rain-wear near the sacred altar."
    },
    facilities: {
      parking: false,
      restrooms: true,
      water: true,
      wheelchair: false,
      lockers: true,
      accommodation: true,
      medical: true
    },
    food: {
      annadanamStatus: 'Limited',
      annadanamTimings: "12:00 PM to 02:00 PM daily",
      breakfast: "Hot Ginger tea distributed between 06:00 AM - 08:00 AM for cold relief",
      lunch: "12:00 PM - 02:00 PM (Simple energy-rich meals: khichdi, roti, jaggery, warm soup)",
      dinner: "06:30 PM - 08:00 PM (Simple rice, dal, and roti by local bhandaras)",
      capacity: 1000,
      diningHallLocation: "GMVN Food & Shelter Compound, Main Kedarnath Pathway",
      prasadamList: [
        { name: "Panchamrit Bhasma Packet", type: "Prasad", price: 30, free: false, collectionPoint: "Main Temple Exit Counter" },
        { name: "Traditional Himalayan walnut-raisin packet", type: "Dry Fruits", price: 100, free: false, collectionPoint: "Badri-Kedar Committee counter" },
        { name: "Holy Thread (Molly)", type: "Auspicious Thread", price: 0, free: true, collectionPoint: "Mandir Entry Pillar" }
      ]
    },
    contact: {
      phone: "+91-135-2430261",
      website: "https://badrinath-kedarnath.gov.in",
      email: "info@bkpc.gov.in"
    },
    timeline: [
      { time: "04:00 AM", event: "Morning cleaning & temple inner door unlock", type: "general" },
      { time: "04:30 AM", event: "Maha Abhishekam and Puja", type: "seva" },
      { time: "06:00 AM", event: "General public darshan opens", type: "darshan" },
      { time: "01:00 PM", event: "Noon rituals & short break preparation", type: "seva" },
      { time: "03:00 PM", event: "Temple gates close for afternoon cleaning", type: "general" },
      { time: "05:00 PM", event: "Gate opens for grand Shringar & Evening Aarti", type: "seva" },
      { time: "07:30 PM", event: "Shiva Tandava Stotra and Vedic chanting", type: "seva" },
      { time: "08:30 PM", event: "Shayan Aarti (Closing prayer chanting)", type: "seva" },
      { time: "09:00 PM", event: "Gates closed for security check", type: "general" }
    ],
    crowdLevel: 'High',
    crowdTrend: [
      { hour: "05:00 AM", count: 80, text: "Abhishekam peak - high queue density" },
      { hour: "09:00 AM", count: 90, text: "Maximum line size - helicopters and hikers arrive" },
      { hour: "01:00 PM", count: 40, text: "Slight decrease during freezing winds" },
      { hour: "06:00 PM", count: 95, text: "Peak spiritual atmosphere during Evening Aarti" },
      { hour: "08:30 PM", count: 30, text: "Wind chilly - rush decreases rapidly" }
    ],
    weather: {
      temp: 8,
      text: "Chilly & Snow Forecast",
      forecast: "Expect snowy showers after 03:00 PM. High frost at night.",
      warning: "Heavy travel warning: Warm thermals, oxygen canisters, and non-skid boots required."
    },
    festivals: [
      { name: "Kapat Opening (Portals Open)", date: "May 3, 2026", countdown: "Passed", description: "The annual spring reopening of portals after 6 winter months, surrounded by Vedic chants." },
      { name: "Kapat Closing (Portals Close)", date: "November 11, 2026", countdown: "152 Days", description: "The closure ceremony when the sacred deity is transitioned to winter retreat at Ukhimath." }
    ],
    nearbyServices: [
      { name: "GMVN Kedarnath Tourist Bungalow", type: "Hotel", rating: 4.1, distance: "0.2 km", address: "Main Base Camp, Temple path" },
      { name: "Garhwal Pure Veg Kitchen", type: "Restaurant", rating: 4.3, distance: "0.1 km", address: "Pathway food corridor" },
      { name: "Kedarnath Emergency Medical Center", type: "Hospital", rating: 4.5, distance: "0.3 km", address: "Adjacent to Helipad Base" },
      { name: "Punjab National Bank Outdoor ATM", type: "ATM", rating: 3.8, distance: "0.4 km", address: "GMVN Guest reception corridor" }
    ],
    liveStreamUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "meenakshi",
    name: "Meenakshi Temple",
    originalName: "மதுரை மீனாட்சி அம்மன் கோவில்",
    deity: "Goddess Meenakshi (Parvati) & Sundareswarar (Shiva)",
    state: "Tamil Nadu",
    city: "Madurai",
    district: "Madurai",
    rating: 4.8,
    isPopular: false,
    description: "Spanning 14 sprawling acres in the ancient heart of Madurai city, the Meenakshi Temple features 14 majestic multi-colored Gopurams decorated with thousands of concrete deities. It is the absolute epitome of complex classical visual architecture of Pandyan rulers.",
    history: "Founded by Indra, lord of gods, as described in scriptures, the modern stone structures were expanded in consecutive stages by the Pandyan Empire and extensively detailed during the Nayaka Rule of Madurai (16-17th Century). Its multi-pillared halls are an absolute mathematical wonder.",
    established: "12th Century CE",
    architecture: "Dravidian Gopuram style",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    location: { lat: 9.9195, lng: 78.1193 },
    timings: {
      opening: "05:00 AM",
      closing: "10:00 PM (Temple closed between 12:30 PM & 04:00 PM)",
      morningDarshan: "06:00 AM - 12:00 PM",
      eveningDarshan: "04:30 PM - 09:30 PM",
      specialDarshan: "07:00 AM - 11:00 AM (Abhisekham Seeghra Darshan pass)"
    },
    dressCode: {
      men: "Must wear Veshti (Dhoti) with Angavastram, shirt, or formal trousers. Lungis, caps, waistcoats, or chest-uncovered wear strictly restricted.",
      women: "Saree, Half-saree, or traditional churidar with dupatta. Leggings, skin-tight pants, sleeveless wear, or modern jeans strictly banned.",
      restricted: "Infringements on regional attire will lead to cancellation of entry ticket."
    },
    facilities: {
      parking: true,
      restrooms: true,
      water: true,
      wheelchair: true,
      lockers: true,
      accommodation: false,
      medical: true
    },
    food: {
      annadanamStatus: 'Available',
      annadanamTimings: "11:30 AM to 01:30 PM daily",
      breakfast: "No breakfast available (Traditional temple Prasadam stall opens at 07:00 AM)",
      lunch: "11:30 AM - 01:30 PM (Grand Tamil Style Annaprasadam: rice, sambar, kootu, rasam, payasam free)",
      dinner: "No dinner (Mild prasad distribution in queue halls)",
      capacity: 3000,
      diningHallLocation: "Srimath Tarigonda Annadhanam Mandapam, East Tower Gate",
      prasadamList: [
        { name: "Meenakshi Ladoo", type: "Ladoo", price: 20, free: false, collectionPoint: "Inner Temple Counters" },
        { name: "Panchamirtham Pot", type: "Prasad Sweet", price: 45, free: false, collectionPoint: "Prasad counter complex" },
        { name: "Puliotharai (Tamarind Rice)", type: "Rice", price: 10, free: false, collectionPoint: "Exit pathway stall" }
      ]
    },
    contact: {
      phone: "+91-4522349811",
      website: "https://maduraimeenakshi.org",
      email: "contact@maduraimeenakshi.org"
    },
    timeline: [
      { time: "05:00 AM", event: "Nadaswaram Instrumental & Temple door opens", type: "general" },
      { time: "05:30 AM", event: "Thiruvananthal Puja", type: "seva" },
      { time: "06:00 AM", event: "Morning Sarvadharshanam begins", type: "darshan" },
      { time: "11:30 AM", event: "Annadanam lunch starts at Annadhanam complex", type: "food" },
      { time: "12:30 PM", event: "Sanctum doors close for afternoon break", type: "general" },
      { time: "04:00 PM", event: "Re-opening of Gopuram gates and evening entry", type: "general" },
      { time: "07:00 PM", event: "Evening Deeparadhanai (Candles and aarti display)", type: "seva" },
      { time: "09:00 PM", event: "Palliyarai Pooja (Resting procession of Lord to Goddess chamber)", type: "seva" },
      { time: "10:00 PM", event: "Final Closing of East Gopuram Gate", type: "general" }
    ],
    crowdLevel: 'Low',
    crowdTrend: [
      { hour: "06:00 AM", count: 40, text: "Calm morning space" },
      { hour: "10:00 AM", count: 75, text: "Healthy visitor density - Abhishekam rush" },
      { hour: "05:00 PM", count: 65, text: "Pleasant evening crowds" },
      { hour: "08:30 PM", count: 90, text: "Extremely Busy - Palliyarai Pooja is highly famous" }
    ],
    weather: {
      temp: 38,
      text: "Sunny & Humid",
      forecast: "Extreme south Indian heat during day. Inner stone galleries are cool.",
      warning: "Wear soft cotton socks to avoid hot pathways in outer open courtyard corridors."
    },
    festivals: [
      { name: "Chithirai Festival", date: "April 18, 2026", countdown: "Passed", description: "The legendary 10-day carnival commemorating the grand union of Goddess Meenakshi with Lord Sundareswarar." },
      { name: "Avani Moola Festival", date: "August 28, 2026", countdown: "77 Days", description: "Annual celebration reviving the divine plays (Thiruvilaiyadal) of Shiva in the ancient city." }
    ],
    nearbyServices: [
      { name: "The Heritage Madurai Resort", type: "Hotel", rating: 4.7, distance: "2.5 km", address: "Melakkal road, Madurai" },
      { name: "Murugan Idli Shop (Iconic)", type: "Restaurant", rating: 4.8, distance: "0.3 km", address: "West Tower Street Corner" },
      { name: "Meenakshi Mission Hospital", type: "Hospital", rating: 4.5, distance: "4.2 km", address: "Lake Area, Melur Road" },
      { name: "ICICI Bank ATM Spot", type: "ATM", rating: 4.2, distance: "0.1 km", address: "Chithirai Street Junction" }
    ],
    liveStreamUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "goldentemple",
    name: "Harmandir Sahib (Golden Temple)",
    originalName: "ಶ್ರೀ ಹರ್ಮಂದಿರ್ ಸಾಹಿಬ್",
    deity: "Guru Granth Sahib",
    state: "Punjab",
    city: "Amritsar",
    district: "Amritsar",
    rating: 4.95,
    isPopular: true,
    description: "Revered globally as the Harmandir Sahib, the Golden Temple is the pre-eminent spiritual pilgrimage site of Sikhism. Built around a beautiful holy pool (Amrit Sarovar), its absolute golden exterior stands as an architectural representation of cosmic peace, equality, and unceasing humanitarian support.",
    history: "Founded by the fourth Sikh Guru, Guru Ram Das, in 1577. The construction was completed by Guru Arjan Dev in 1604, who installed the first copy of Adi Granth. In the early 19th Century, Maharaja Ranjit Singh overlaid the upper floors with ultra-pure copper plates gilded with 500 kg of pure gold leaf.",
    established: "1604 CE",
    architecture: "Indo-Islamic and Mughal-Sikh Fusion",
    image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1200&q=80",
    location: { lat: 31.6200, lng: 74.8765 },
    timings: {
      opening: "03:00 AM",
      closing: "12:00 AM (Always Open to visitors conceptually)",
      morningDarshan: "04:00 AM - 12:00 PM",
      eveningDarshan: "01:00 PM - 11:30 PM",
      specialDarshan: "04:30 AM - 06:15 AM (Prakash Purab procession arrival)"
    },
    dressCode: {
      men: "Salwar Kameez, Kurta, or modest formal shirts and trousers. Head must remain completely covered with a handkerchief/turban at all times.",
      women: "Salwar Suit, traditional long dress, or modest top and trousers. Head must remain covered with dupatta or scarf at all times.",
      restricted: "Strictly forbidden: Bare head, shorts, skirts, sleeveless tops, cigarettes, tobacco, or alcohol products anywhere inside the outer compound."
    },
    facilities: {
      parking: true,
      restrooms: true,
      water: true,
      wheelchair: true,
      lockers: true,
      accommodation: true,
      medical: true
    },
    food: {
      annadanamStatus: 'Available',
      annadanamTimings: "24 Hours Continuous Service (Largest Free Kitchen in the World)",
      breakfast: "24 Hours (Spiced Tea, fresh Roti, Lentils, Chickpeas)",
      lunch: "24 Hours (Hot Dal-Makhani, Kadhi-Chawal, Roti, Kheer, salad)",
      dinner: "24 Hours (Langar meals distributed with deep devotion by volunteers)",
      capacity: 100000,
      diningHallLocation: "Guru Ram Das Langar Hall (Serves over 100,000 pilgrims every single day)",
      prasadamList: [
        { name: "Karah Prasad (Warm wheat flour prasad with pure ghee)", type: "Holy Halwa", price: 0, free: true, collectionPoint: "Langar Hall exit corridor" },
        { name: "Special Dry Pinni Prasad", type: "Sweet Laddu", price: 50, free: false, collectionPoint: "Prasad ticketing counter" }
      ]
    },
    contact: {
      phone: "+91-1832553957",
      website: "https://sgpc.net",
      email: "info@sgpc.net"
    },
    timeline: [
      { time: "03:00 AM", event: "Kiwad (Gates) Open ceremony with divine hymn chanting", type: "general" },
      { time: "04:15 AM", event: "Prakash Purab (Bringing holy Guru Granth Sahib from Akal Takht)", type: "seva" },
      { time: "05:00 AM", event: "Asa di Var kirtan recitation", type: "seva" },
      { time: "06:00 AM", event: "Hukamnama publication (Holy random message reading of the day)", type: "darshan" },
      { time: "11:00 AM", event: "Voluntary Langer shifts peak", type: "food" },
      { time: "07:30 PM", event: "Evening Rehras Sahib prayers", type: "seva" },
      { time: "09:30 PM", event: "Sukhhasan ceremony (Holy Book returned to Akal Takht chamber)", type: "seva" },
      { time: "11:00 PM", event: "Cleaning of the Amrit Sarovar banks with milk-infused water", type: "general" }
    ],
    crowdLevel: 'Medium',
    crowdTrend: [
      { hour: "04:00 AM", count: 70, text: "Peak morning Prakash ceremony crowd" },
      { hour: "09:00 AM", count: 55, text: "Healthy crowd flow in bridge queue" },
      { hour: "01:00 PM", count: 45, text: "Lively yet fast distribution flow" },
      { hour: "07:00 PM", count: 95, text: "Extremely Busy - Golden lights reflect on holy pool water" },
      { hour: "11:00 PM", count: 35, text: "Calm and peaceful night vibes" }
    ],
    weather: {
      temp: 32,
      text: "Pleasant Wind",
      forecast: "Cozy breeze from the north. High summer temperatures during day, cooler nights.",
      warning: "Ensure your head is covered completely inside or your entry will be restricted."
    },
    festivals: [
      { name: "Guru Nanak Gurpurab", date: "November 24, 2026", countdown: "165 Days", description: "Grand celebration of Guru Nanak Dev Ji birth anniversary, lit up by 100,000 candles." },
      { name: "Vaisakhi Chariot", date: "April 14, 2026", countdown: "Passed", description: "Harvest and founding anniversary of Khalsa army command." }
    ],
    nearbyServices: [
      { name: "Sada Pind Boutique Village Hotel", type: "Hotel", rating: 4.6, distance: "4.5 km", address: "By-pass Road, Amritsar Outskirts" },
      { name: "Kesar Da Dhaba (Heritage Eatery)", type: "Restaurant", rating: 4.8, distance: "0.5 km", address: "Chowk Passian, near Golden Temple" },
      { name: "Amritsar Multi Specialty Hospital", type: "Hospital", rating: 4.4, distance: "1.8 km", address: "Mall Road Junction" },
      { name: "State Bank of India Langar Gate ATM", type: "ATM", rating: 4.3, distance: "0.1 km", address: "Main Bazaar Plaza Gate" }
    ],
    liveStreamUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "jagannath",
    name: "Jagannath Temple Puri",
    originalName: "ଶ୍ରୀ ଜଗନ୍ନାଥ ମନ୍ଦିର",
    deity: "Lord Jagannath, Balabhadra & Subhadra",
    state: "Odisha",
    city: "Puri",
    district: "Puri",
    rating: 4.85,
    isPopular: false,
    description: "Located on the divine eastern coast of Bay of Bengal, the sacred Jagannath Temple is a core Char Dham pilgrimage site representing spiritual royalty and mysterious celestial occurrences. It houses the wooden deities Lord Jagannath, Balabhadra, and Subhadra who are periodically replaced.",
    history: "Commissioned during the 12th Century by King Anatavarman Chodaganga Deva of the Eastern Ganga Dynasty, the temple stands as a supreme monument of regional stone geometry. Its central flag unfurls in a direction reverse to wind flow, and its grand shadow is never visible on the ground.",
    established: "12th Century CE",
    architecture: "Kalinga Sacred Stone Architecture",
    image: "https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1200&q=80",
    location: { lat: 19.8049, lng: 85.8179 },
    timings: {
      opening: "05:00 AM",
      closing: "11:50 PM",
      morningDarshan: "06:30 AM - 01:00 PM",
      eveningDarshan: "04:00 PM - 10:00 PM",
      specialDarshan: "05:30 AM - 06:30 AM (Mangala Alati special entrance)"
    },
    dressCode: {
      men: "Ethical Indian clothing like clean Dhoti-Kurta or Pyjamas. Leather shoes, bags, heavy metal belts, or shorts are strictly banned inside the main gate.",
      women: "Saree, salwar suit with dupatta. Modern short skirts, sleeveless attire, or jeans are restricted.",
      restricted: "Non-Hindus or foreigners of non-Indian origin are strictly restricted from entering the inner sanctum due to centuries-old tradition."
    },
    facilities: {
      parking: true,
      restrooms: true,
      water: true,
      wheelchair: true,
      lockers: true,
      accommodation: true,
      medical: true
    },
    food: {
      annadanamStatus: 'Available',
      annadanamTimings: "02:00 PM to 05:00 PM daily (The Mahaprasad Abadha)",
      breakfast: "Occasional Khuda bhog distributed in inner compartments",
      lunch: "02:00 PM - 05:00 PM (Simulated cooking in 7 clay pots placed atop each other over holy furnace: Rice, Dal, vegetable curry, sweet khaja)",
      dinner: "08:00 PM - 10:30 PM (Mild distribution in Anand Bazar field inside temple complex)",
      capacity: 35000,
      diningHallLocation: "Anand Bazar food field, southeast segment of outer courtyard",
      prasadamList: [
        { name: "Kanika Sweet Ghee Rice", type: "Rice Sweet", price: 40, free: false, collectionPoint: "Anand Bazar" },
        { name: "Sweet Jagannath Khaja Basket", type: "Dessert Sweet", price: 50, free: false, collectionPoint: "Outer Gate counters" },
        { name: "Arna Abadha Meal Thali", type: "Full Meal", price: 80, free: false, collectionPoint: "Langer distribution area" }
      ]
    },
    contact: {
      phone: "+91-6752222002",
      website: "https://shreejagannatha.in",
      email: "helpdesk@purityjagannath.org"
    },
    timeline: [
      { time: "05:00 AM", event: "Doors unlock & Mangala Alati worship", type: "seva" },
      { time: "06:30 AM", event: "Shringar or deity dressing ritual", type: "seva" },
      { time: "07:30 AM", event: "General Darshan corridor begins", type: "darshan" },
      { time: "11:00 AM", event: "Sankhaludi Bhog preparation", type: "seva" },
      { time: "01:00 PM", event: "Noon break for deities' rest", type: "general" },
      { time: "04:00 PM", event: "Re-opening of Lion's Gate and afternoon darshan", type: "darshan" },
      { time: "05:30 PM", event: "Abadha Mahaprasad distribution in Anand Bazar", type: "food" },
      { time: "09:00 PM", event: "Chandan Lagi floral paste seva", type: "seva" },
      { time: "11:50 PM", event: "Late night Shayan seva & door lock", type: "general" }
    ],
    crowdLevel: 'High',
    crowdTrend: [
      { hour: "05:00 AM", count: 85, text: "High rush for Mangala Alati" },
      { hour: "09:00 AM", count: 65, text: "Moderate general queues" },
      { hour: "02:00 PM", count: 90, text: "Peak rush - Mahaprasad Mahotsav in Anand Bazar" },
      { hour: "06:00 PM", count: 70, text: "Pleasant seaside evening crowd" },
      { hour: "10:00 PM", count: 50, text: "Peaceful late night walk" }
    ],
    weather: {
      temp: 30,
      text: "Humid Seaside Breeze",
      forecast: "Strong evening ocean breeze, pleasant skies, light showers predicted.",
      warning: "Heavily crowded during hot noon hours. Stand under misting fans near corridors if needed."
    },
    festivals: [
      { name: "Ratha Yatra Chariot Festival", date: "June 25, 2026", countdown: "13 Days", description: "The divine world-famous colossal wooden chariot procession of three deities traversing Goundicha Temple." },
      { name: "Snana Yatra Water Festival", date: "June 14, 2026", countdown: "2 Days", description: "Sacred bathing ceremony of Lord Jagannath with 108 gold pots of herbal incense water." }
    ],
    nearbyServices: [
      { name: "Mayfair Waves Beach Resort Puri", type: "Hotel", rating: 4.8, distance: "2.1 km", address: "Chakra Tirtha Road, Puri Beach" },
      { name: "Wild Grass Odia Satvik Restaurant", type: "Restaurant", rating: 4.5, distance: "1.1 km", address: "VIP Road, near Grand Canopy" },
      { name: "Puri District Headquarters Hospital", type: "Hospital", rating: 4.1, distance: "1.8 km", address: "Grand Road, Puri Town" }
    ],
    liveStreamUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  }
];

export const MULTILINGUAL_DICTIONARY: Record<string, Record<string, string>> = {
  en: {
    discoverTemples: "Discover Temples • Plan Darshan • Experience Spirituality",
    tagline: "DarshanGuide — Your complete spiritual pilgrimage planning and discovery companion.",
    searchPlaceholder: "Search by Temple Name, Deity, City, State...",
    detectLocation: "Use current Location / GPS",
    popularTemples: "Popular Temples",
    upcomingFestivals: "Upcoming Festivals",
    liveDarshan: "Live Stream / Virtual Tour",
    exploreAll: "Explore All Temples",
    nearbyTemples: "Nearby Temples Based on GPS",
    darshanPlanner: "AI Darshan Plan Builder",
    spiritualBot: "AI Spiritual Assistant",
    annadanam: "Annadanam & Prasadam",
    dailyTimeline: "Daily Shrine Schedule",
    reviews: "Reviews & Pilgrim Experiences",
    nearbyServicesLabel: "Essential Nearby Services",
    weatherTitle: "Live Temple Weather",
    crowdPrediction: "Live Crowd Prediction",
    dressCodeTitle: "Mandatory Dress Protocol",
    facilitiesTitle: "Temple Facilities Checklist",
    historyTitle: "Ancient History & Heritage",
    contactTitle: "Trust Contact & Office Details",
    openNow: "Open Now",
    closed: "Closed",
    available: "Available",
    limited: "Limited Spares",
    lowCrowd: "Low Crowds (Highly Recommended)",
    mediumCrowd: "Moderate Crowd (Normal)",
    highCrowd: "Extreme Rush",
    menDress: "Men Attire",
    womenDress: "Women Attire",
    restrictedDress: "Strict Restrictions",
    adminDashboard: "Admin Management Desk",
    authButton: "Devotee Login / Register",
    languageSwitcher: "Switch Language",
    chatGreeting: "Namaste! I am your AI Spiritual Guide designed for DarshanGuide. Ask me anything regarding temple histories, timing systems, holy fasting protocols, or transport suggestions.",
    
    // Temple names & labels mapping
    "Tirumala Venkateswara Temple": "Tirumala Venkateswara Temple",
    "Kashi Vishwanath Temple": "Kashi Vishwanath Temple",
    "Kedarnath Temple": "Kedarnath Temple",
    "Meenakshi Temple": "Meenakshi Temple",
    "Harmandir Sahib (Golden Temple)": "Harmandir Sahib (Golden Temple)",
    "Jagannath Temple Puri": "Jagannath Temple Puri",
    "Lord Venkateswara (Balaji)": "Lord Venkateswara (Balaji)",
    "Lord Shiva (Vishwanatha)": "Lord Shiva (Vishwanatha)",
    "Lord Shiva (Sadashiva)": "Lord Shiva (Sadashiva)",
    "Goddess Meenakshi (Parvati) & Sundareswarar (Shiva)": "Goddess Meenakshi (Parvati) & Sundareswarar (Shiva)",
    "Guru Granth Sahib": "Guru Granth Sahib",
    "Lord Jagannath, Balabhadra & Subhadra": "Lord Jagannath, Balabhadra & Subhadra",
    "Andhra Pradesh": "Andhra Pradesh",
    "Uttar Pradesh": "Uttar Pradesh",
    "Uttarakhand": "Uttarakhand",
    "Tamil Nadu": "Tamil Nadu",
    "Punjab": "Punjab",
    "Odisha": "Odisha",
    "Tirupati": "Tirupati",
    "Varanasi": "Varanasi",
    "Kedarnath Valley": "Kedarnath Valley",
    "Madurai": "Madurai",
    "Amritsar": "Amritsar",
    "Puri": "Puri",
    "Filter by Deity:": "Filter by Deity:",
    "Filter by State:": "Filter by State:",
    "All Deities": "All Deities",
    "All States": "All States",
    "Deity:": "Deity:",
    "Wheelchair Accessible": "Wheelchair Accessible",
    "Annadanam Available": "Annadanam Available",
    "No Shrines Matching Filters": "No Shrines Matching Filters",
    "Please try modifying your keywords or select another deity focus.": "Please try modifying your keywords or select another deity focus.",
    "GPS Distance Uncalculated": "GPS Distance Uncalculated",
    "Details": "Details",
    "Trust Verified": "Trust Verified",
    "6 grand shrines logged": "6 grand shrines logged",
    "🕉️ Sacred Devasthanam Aggregator": "🕉️ Sacred Devasthanam Aggregator",
    "Upcoming Religious Carnivals & Celebrations": "Upcoming Religious Carnivals & Celebrations",

    // Descriptions
    "Perched atop the seven hills of Seshachalam, Tirumala Venkateswara Temple is the most visited, wealthiest, and spiritually radiant temple in the world. Revered as Kaliyuga Vaikuntam, this historical shrine represents pristine Dravidian architecture and eternal spiritual energy.": "Perched atop the seven hills of Seshachalam, Tirumala Venkateswara Temple is the most visited, wealthiest, and spiritually radiant temple in the world. Revered as Kaliyuga Vaikuntam, this historical shrine represents pristine Dravidian architecture and eternal spiritual energy.",
    "Located on the sacred western bank of the holy Ganges river in Varanasi, Kashi Vishwanath contains the venerated Jyotirlinga, the golden spire of spiritual axis representing the cosmic light of Shiva. It represents liberation (Moksha) and timeless continuous prayers.": "Located on the sacred western bank of the holy Ganges river in Varanasi, Kashi Vishwanath contains the venerated Jyotirlinga, the golden spire of spiritual axis representing the cosmic light of Shiva. It represents liberation (Moksha) and timeless continuous prayers.",
    "Nestled in the majestic snow-clad Garhwal Himalayas at 3,583 meters above sea level near Mandakini river, Kedarnath represents the highest of 12 Jyotirlingas, representing eternal absolute presence of Lord Shiva as Pandavas' divine redeemer.": "Nestled in the majestic snow-clad Garhwal Himalayas at 3,583 meters above sea level near Mandakini river, Kedarnath represents the highest of 12 Jyotirlingas, representing eternal absolute presence of Lord Shiva as Pandavas' divine redeemer.",
    "Spanning 14 sprawling acres in the ancient heart of Madurai city, the Meenakshi Temple features 14 majestic multi-colored Gopurams decorated with thousands of concrete deities. It is the absolute epitome of complex classical visual architecture of Pandyan rulers.": "Spanning 14 sprawling acres in the ancient heart of Madurai city, the Meenakshi Temple features 14 majestic multi-colored Gopurams decorated with thousands of concrete deities. It is the absolute epitome of complex classical visual architecture of Pandyan rulers.",
    "Revered globally as the Harmandir Sahib, the Golden Temple is the pre-eminent spiritual pilgrimage site of Sikhism. Built around a beautiful holy pool (Amrit Sarovar), its absolute golden exterior stands as an architectural representation of cosmic peace, equality, and unceasing humanitarian support.": "Revered globally as the Harmandir Sahib, the Golden Temple is the pre-eminent spiritual pilgrimage site of Sikhism. Built around a beautiful holy pool (Amrit Sarovar), its absolute golden exterior stands as an architectural representation of cosmic peace, equality, and unceasing humanitarian support.",
    "Located on the divine eastern coast of Bay of Bengal, the sacred Jagannath Temple is a core Char Dham pilgrimage site representing spiritual royalty and mysterious celestial occurrences. It houses the wooden deities Lord Jagannath, Balabhadra, and Subhadra who are periodically replaced.": "Located on the divine eastern coast of Bay of Bengal, the sacred Jagannath Temple is a core Char Dham pilgrimage site representing spiritual royalty and mysterious celestial occurrences. It houses the wooden deities Lord Jagannath, Balabhadra, and Subhadra who are periodically replaced."
  },
  te: {
    discoverTemples: "దేవాలయాలను కనుగొనండి • दर्शनం ప్లాన్ చేయండి • ఆధ్యాత్మికతను అనుభవించండి",
    tagline: "దర్శన్ గైడ్ — మీ పూర్తి ఆధ్యాత్మిక తీర్థయాత్ర ప్రణాళిక మరియు అన్వేషణ తోడు.",
    searchPlaceholder: "దేవుడు, నగరం, రాష్ట్రం లేదా ఆలయ పేరు ద్వారా శోధించండి...",
    detectLocation: "ప్రస్తుత స్థానాన్ని గుర్తించు (GPS)",
    popularTemples: "ప్రసిద్ధ దేవాలయాలు",
    upcomingFestivals: "రాబోయే పండుగలు",
    liveDarshan: "ప్రత్యక్ష ప్రసారము / వర్చువల్ టూర్",
    exploreAll: "అన్ని దేవాలయాలను అన్వేషించండి",
    nearbyTemples: "GPS ఆధారంగా సమీప దేవాలయాలు",
    darshanPlanner: "AI దర్శన ప్రణాళికాకర్త",
    spiritualBot: "AI ఆధ్యాత్మిక అసిస్టెంట్",
    annadanam: "అన్నదానం & ప్రసాదం వివరాలు",
    dailyTimeline: "ఆలయ దినచర్యల కాలక్రమం",
    reviews: "భక్తుల అనుభవాలు & సమీక్షలు",
    nearbyServicesLabel: "ఆవశ్యకమైన సమీప సేవలు",
    weatherTitle: "ప్రత్యక్ష వాతావరణం",
    crowdPrediction: "భక్తుల రద్దీ అంచనా",
    dressCodeTitle: "తప్పనిసరి దుస్తుల నిబంధనలు",
    facilitiesTitle: "ఆలయ అందుబాటు సౌకర్యాలు",
    historyTitle: "చారిత్రక నేపధ్యం",
    contactTitle: "ఆలయ కమిటీ సంప్రదింపు వివరాలు",
    openNow: "ప్రస్తుతం తెరిచి ఉంది",
    closed: "మూసివేయబడింది",
    available: "లభ్యత ఉంది",
    limited: "పరిమిత పరిమాణం",
    lowCrowd: "తక్కువ రద్దీ (దర్శనానికి ఉత్తమ సమయం)",
    mediumCrowd: "సాధారణ రద్దీ",
    highCrowd: "భారీ రద్దీ",
    menDress: "పురుషుల దుస్తులు",
    womenDress: "మహిళల దుస్తులు",
    restrictedDress: "निషేధిత దుస్తులు",
    adminDashboard: "అడ్మిన్ డ్యాష్‌బోర్డ్",
    authButton: "భక్తుల లాగిన్ / రిజిస్టర్",
    languageSwitcher: "భాషను మార్చండి",
    chatGreeting: "నమస్తే! నేను మీ AI ఆధ్యాత్మిక సహాయకుడిని. ఆలయాల చరిత్రలు, నియమాలు లేదా ప్రసాద వివరాల గురించి ఏదైనా అడగండి.",

    // Temple names & labels mapping
    "Tirumala Venkateswara Temple": "తిరుమల వేంకటేశ్వర ఆలయం",
    "Kashi Vishwanath Temple": "కాశీ విశ్వనాథ్ దేవాలయం",
    "Kedarnath Temple": "కేదార్‌నాథ్ ఆలయం",
    "Meenakshi Temple": "మీనాక్షి ఆలయం",
    "Harmandir Sahib (Golden Temple)": "హర్మందిర్ సాహిబ్ (స్వర్ణ దేవాలయం)",
    "Jagannath Temple Puri": "పూరి జగన్నాథ ఆలయం",
    "Lord Venkateswara (Balaji)": "శ్రీ వేంకటేశ్వర స్వామి (బాలాజీ)",
    "Lord Shiva (Vishwanatha)": "శివుడు (విశ్వనాథుడు)",
    "Lord Shiva (Sadashiva)": "శివుడు (సదాశివుడు)",
    "Goddess Meenakshi (Parvati) & Sundareswarar (Shiva)": "మీనాక్షీ దేవి (పార్వతి) & సుందరేశ్వరుడు (శివుడు)",
    "Guru Granth Sahib": "గురు గ్రంథ్ సాహిబ్",
    "Lord Jagannath, Balabhadra & Subhadra": "జగన్నాథుడు, బలభద్రుడు & సుభద్ర",
    "Andhra Pradesh": "ఆంధ్రప్రదేశ్",
    "Uttar Pradesh": "ఉత్తరప్రదేశ్",
    "Uttarakhand": "ఉత్తరాఖండ్",
    "Tamil Nadu": "తమిళనాడు",
    "Punjab": "పంజాబ్",
    "Odisha": "ఒడిశా",
    "Tirupati": "తిరుపతి",
    "Varanasi": "వారణాసి",
    "Kedarnath Valley": "కేదార్‌నాథ్ వ్యాలీ",
    "Madurai": "మధురై",
    "Amritsar": "అమృత్‌సర్",
    "Puri": "పూరి",
    "Filter by Deity:": "దేవుని ఆధారంగా ఫిల్టర్:",
    "Filter by State:": "రాష్ట్రం ఆధారంగా ఫిల్టర్:",
    "All Deities": "అన్ని దేవతలు",
    "All States": "అన్ని రాష్ట్రాలు",
    "Deity:": "దేవుడు:",
    "Wheelchair Accessible": "వీల్‌చైర్ సౌకర్యం ఉంది",
    "Annadanam Available": "అన్నదానం అందుబాటులో ఉంది",
    "No Shrines Matching Filters": "ఫిల్టర్‌లకు సరిపోయే ఆలయాలు లేవు",
    "Please try modifying your keywords or select another deity focus.": "దయచేసి మీ శోధన పదాలను మార్చండి లేదా మరొక దేవతను ఎంచుకోండి.",
    "GPS Distance Uncalculated": "GPS దూరం లెక్కించబడలేదు",
    "Details": "వివరాలు",
    "Trust Verified": "ట్రస్ట్ ధృవీకరించబడింది",
    "6 grand shrines logged": "6 మహా క్షేత్రాలు నమోదు చేయబడ్డాయి",
    "🕉️ Sacred Devasthanam Aggregator": "🕉️ పవిత్ర దేవస్థాన సమాహారం",
    "Upcoming Religious Carnivals & Celebrations": "రాబోయే పండుగలు & ఉత్సవాలు",

    // Descriptions
    "Perched atop the seven hills of Seshachalam, Tirumala Venkateswara Temple is the most visited, wealthiest, and spiritually radiant temple in the world. Revered as Kaliyuga Vaikuntam, this historical shrine represents pristine Dravidian architecture and eternal spiritual energy.": "శేషాచలం ఏడు కొండలపై వెలసిన తిరుమల వేంకటేశ్వర ఆలయం ప్రపంచంలోనే అత్యధికంగా సందర్శించే, అత్యంత ధనిక మరియు ఆధ్యాత్మిక కాంతితో విరాజిల్లే ఆలయం. కలియుగ వైకుంఠంగా పూజించబడుతుంది.",
    "Located on the sacred western bank of the holy Ganges river in Varanasi, Kashi Vishwanath contains the venerated Jyotirlinga, the golden spire of spiritual axis representing the cosmic light of Shiva. It represents liberation (Moksha) and timeless continuous prayers.": "వారణాసిలోని పవిత్ర గంగా నది పశ్చిమ ఒడ్డున ఉన్న కాశీ విశ్వనాథ ఆలయంలో పూజనీయమైన జ్యోతిర్లింగం ఉంది, ఇది శివుని కాంతిని సూచిస్తుంది. ఇది మోక్షాన్ని ప్రసాదిస్తుంది.",
    "Nestled in the majestic snow-clad Garhwal Himalayas at 3,583 meters above sea level near Mandakini river, Kedarnath represents the highest of 12 Jyotirlingas, representing eternal absolute presence of Lord Shiva as Pandavas' divine redeemer.": "మందాకిని నదికి సమీపంలో సముద్ర మట్టానికి 3,583 మీటర్ల ఎత్తులో మంచుతో కప్పబడిన గర్హ్వాల్ హిమాలయాలలో ఉన్న కేదార్‌నాథ్ ఆలయం, 12 జ్యోతిర్లింగాలలో అత్యంత ఎత్తైనది.",
    "Spanning 14 sprawling acres in the ancient heart of Madurai city, the Meenakshi Temple features 14 majestic multi-colored Gopurams decorated with thousands of concrete deities. It is the absolute epitome of complex classical visual architecture of Pandyan rulers.": "మధురై నగరంలోని పురాతన గుండెకాయలో 14 ఎకరాల విస్తీర్ణంలో విస్తరించి ఉన్న మీనాక్షి ఆలయం, వేలాది దేవతా విగ్రహాలతో అలంకరించబడిన 14 గంభీరమైన రంగురంగుల గోపురాలను కలిగి ఉంది.",
    "Revered globally as the Harmandir Sahib, the Golden Temple is the pre-eminent spiritual pilgrimage site of Sikhism. Built around a beautiful holy pool (Amrit Sarovar), its absolute golden exterior stands as an architectural representation of cosmic peace, equality, and unceasing humanitarian support.": "ప్రపంచవ్యాప్తంగా హర్మందిర్ సాహిబ్ అని పిలువబడే స్వర్ణ దేవాలయం సిక్కు మతం యొక్క అత్యున్నత ఆధ్యాత్మిక క్షేత్రం. ఇది పవిత్రమైన అమృత్ సరోవర్ చుట్టూ నిర్మించబడింది.",
    "Located on the divine eastern coast of Bay of Bengal, the sacred Jagannath Temple is a core Char Dham pilgrimage site representing spiritual royalty and mysterious celestial occurrences. It houses the wooden deities Lord Jagannath, Balabhadra, and Subhadra who are periodically replaced.": "బంగాళాఖాత పవిత్ర తూర్పు తీరంలో ఉన్న పూరి జగన్నాథ ఆలయం చార్ ధామ్ యాత్రా స్థలాలలో ఒకటి. ఇక్కడ చెక్కతో చేయబడిన జగన్నాథుడు, బలభద్ర, సుభద్ర విగ్రహాలు ఉన్నాయి."
  },
  hi: {
    discoverTemples: "मंदिरों की खोज करें • दर्शन की योजना बनाएं • आध्यात्मिकता का अनुभव करें",
    tagline: "दर्शनगाइड — आपका संपूर्ण आध्यात्मिक तीर्थयात्रा योजना और खोज साथी।",
    searchPlaceholder: "मंदिर का नाम, देवता, शहर या राज्य खोजें...",
    detectLocation: "वर्तमान स्थान का उपयोग करें (GPS)",
    popularTemples: "लोकप्रिय मंदिर",
    upcomingFestivals: "आगामी त्योहार",
    liveDarshan: "लाइव दर्शन / वर्चुअल टूर",
    exploreAll: "सभी मंदिरों का अन्वेषण करें",
    nearbyTemples: "जीपीएस के आधार पर नजदीकी मंदिर",
    darshanPlanner: "AI तीर्थयात्रा योजनाकार",
    spiritualBot: "AI आध्यात्मिक सहायक",
    annadanam: "अन्नदानम् और महाप्रसाद",
    dailyTimeline: "दैनिक मंदिर समयरेखा",
    reviews: "श्रद्धालुओं की समीक्षाएं",
    nearbyServicesLabel: "निकटवर्ती आवश्यक सेवाएं",
    weatherTitle: "लाइव मौसम की जानकारी",
    crowdPrediction: "भक्तों की भीड़ का पूर्वानुमान",
    dressCodeTitle: "अनिवार्य पोशाक नियम (ड्रेस कोड)",
    facilitiesTitle: "मंदिर सुविधाएं",
    historyTitle: "प्राचीन इतिहास और संस्कृति",
    contactTitle: "संपर्क एवं कार्यालय विवरण",
    openNow: "अभी खुला है",
    closed: "बंद है",
    available: "उपलब्ध",
    limited: "सीमित मात्रा",
    lowCrowd: "कम भीड़ (दर्शन के लिए उत्तम)",
    mediumCrowd: "मध्यम भीड़ (सामान्य)",
    highCrowd: "अत्यधिक भीड़",
    menDress: "पुरुषों के वस्त्र",
    womenDress: "महिला वस्त्र",
    restrictedDress: "वर्जित वस्त्र",
    adminDashboard: "एडमिन नियंत्रण केंद्र",
    authButton: "भक्त लॉगिन / पंजीकरण",
    languageSwitcher: "भाषा बदलें",
    chatGreeting: "नमस्ते! मैं आपका AI आध्यात्मिक मार्गदर्शक हूँ। मुझसे मंदिरों के इतिहास, समय चक्र, उपवास और अन्य तीर्थ यात्रा प्रक्रियाओं के बारे में पूछें.",

    // Temple names & labels mapping
    "Tirumala Venkateswara Temple": "तिरुमला वेंकटेश्वर मंदिर",
    "Kashi Vishwanath Temple": "काशी विश्वनाथ मंदिर",
    "Kedarnath Temple": "केदारनाथ मंदिर",
    "Meenakshi Temple": "मीनाक्षी मंदिर",
    "Harmandir Sahib (Golden Temple)": "हरमंदिर साहिब (स्वर्ण मंदिर)",
    "Jagannath Temple Puri": "जगन्नाथ मंदिर पुरी",
    "Lord Venkateswara (Balaji)": "भगवान वेंकटेश्वर (बालाजी)",
    "Lord Shiva (Vishwanatha)": "भगवान शिव (विश्वनाथ)",
    "Lord Shiva (Sadashiva)": "भगवान शिव (सदाशिव)",
    "Goddess Meenakshi (Parvati) & Sundareswarar (Shiva)": "देवी मीनाक्षी (पार्वती) और सुंदरेश्वर (शिव)",
    "Guru Granth Sahib": "गुरु ग्रंथ साहिब",
    "Lord Jagannath, Balabhadra & Subhadra": "भगवान जगन्नाथ, बलभद्र और सुभद्रा",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Uttar Pradesh": "उत्तर प्रदेश",
    "Uttarakhand": "उत्तराखंड",
    "Tamil Nadu": "तमिलनाडु",
    "Punjab": "पंजाब",
    "Odisha": "ओडिशा",
    "Tirupati": "तिरुपति",
    "Varanasi": "वाराणसी",
    "Kedarnath Valley": "केदारनाथ घाटी",
    "Madurai": "मधुरै",
    "Amritsar": "अमृतसर",
    "Puri": "पुरी",
    "Filter by Deity:": "देवता द्वारा फ़िल्टर:",
    "Filter by State:": "राज्य द्वारा फ़िल्टर:",
    "All Deities": "सभी देवता",
    "All States": "सभी राज्य",
    "Deity:": "देवता:",
    "Wheelchair Accessible": "व्हीलचेयर सुलभ",
    "Annadanam Available": "अन्नदान उपलब्ध",
    "No Shrines Matching Filters": "फ़िल्टर से मेल खाता कोई मंदिर नहीं मिला",
    "Please try modifying your keywords or select another deity focus.": "कृपया अपने खोज शब्दों को बदलें या दूसरा देवता चुनें।",
    "GPS Distance Uncalculated": "जीपीएस दूरी की गणना नहीं की गई",
    "Details": "विवरण देखें",
    "Trust Verified": "विश्वस्त प्राधिकारी",
    "6 grand shrines logged": "6 प्रमुख मंदिरों की जानकारी दर्ज",
    "🕉️ Sacred Devasthanam Aggregator": "🕉️ पावन देवस्थानम संकलन",
    "Upcoming Religious Carnivals & Celebrations": "आगामी धार्मिक उत्सव और समारोह",

    // Descriptions
    "Perched atop the seven hills of Seshachalam, Tirumala Venkateswara Temple is the most visited, wealthiest, and spiritually radiant temple in the world. Revered as Kaliyuga Vaikuntam, this historical shrine represents pristine Dravidian architecture and eternal spiritual energy.": "शेषचलम की सात पहाड़ियों पर स्थित, तिरुमला वेंकटेश्वर मंदिर दुनिया का सबसे अधिक देखा जाने वाला और आध्यात्मिक रूप से दीप्तिमान मंदिर है, जिसे कलियुग वैकुंठ के रूप में पूजा जाता है।",
    "Located on the sacred western bank of the holy Ganges river in Varanasi, Kashi Vishwanath contains the venerated Jyotirlinga, the golden spire of spiritual axis representing the cosmic light of Shiva. It represents liberation (Moksha) and timeless continuous prayers.": "वाराणसी में पवित्र गंगा नदी के तट पर स्थित, काशी विश्वनाथ मंदिर में पूजनीय ज्योतिर्लिंग है, जो शिव के ब्रह्मांडीय प्रकाश का प्रतिनिधित्व करता है और मोक्ष प्रदान करता है।",
    "Nestled in the majestic snow-clad Garhwal Himalayas at 3,583 meters above sea level near Mandakini river, Kedarnath represents the highest of 12 Jyotirlingas, representing eternal absolute presence of Lord Shiva as Pandavas' divine redeemer.": "मंदाकिनी नदी के पास समुद्र तल से 3,583 मीटर ऊपर बर्फ से ढके हिमालय में स्थित, केदारनाथ 12 ज्योतिर्लिंगों में सबसे ऊंचा है और शिव की शाश्वत उपस्थिति का प्रतीक है।",
    "Spanning 14 sprawling acres in the ancient heart of Madurai city, the Meenakshi Temple features 14 majestic multi-colored Gopurams decorated with thousands of concrete deities. It is the absolute epitome of complex classical visual architecture of Pandyan rulers.": "मदुरै शहर के प्राचीन हृदय में 14 एकड़ में फैला मीनाक्षी मंदिर, हजारों कंक्रीट देवताओं से सजे 14 राजसी बहु-रंगीन गोपुरमों से सुसज्जित है।",
    "Revered globally as the Harmandir Sahib, the Golden Temple is the pre-eminent spiritual pilgrimage site of Sikhism. Built around a beautiful holy pool (Amrit Sarovar), its absolute golden exterior stands as an architectural representation of cosmic peace, equality, and unceasing humanitarian support.": "पवित्र अमृत् सरोवर सरोवर के चारों ओर निर्मित स्वर्ण मंदिर सिख धर्म का सबसे प्रमुख आध्यात्मिक तीर्थस्थल है, जो ब्रह्मांडीय शांति और समानता का प्रतिनिधित्व करता है।",
    "Located on the divine eastern coast of Bay of Bengal, the sacred Jagannath Temple is a core Char Dham pilgrimage site representing spiritual royalty and mysterious celestial occurrences. It houses the wooden deities Lord Jagannath, Balabhadra, and Subhadra who are periodically replaced.": "बंगाल की खाड़ी के तट पर स्थित पवित्र जगन्नाथ मंदिर एक प्रमुख चार धाम तीर्थ स्थल है। यहाँ लकड़ी से निर्मित भगवान जगन्नाथ, बलभद्र और सुभद्रा की मूर्तियाँ स्थापित हैं।"
  },
  ta: {
    discoverTemples: "கோவில்களைக் கண்டறிந்து • தரிசனம் திட்டமிட்டு • ஆன்மீகத்தை உணருங்கள்",
    tagline: "தரிசனவழிகாட்டி — உங்களின் முழுமையான ஆன்மீகத் திருத்தலத் திட்டமிடல் மற்றும் தேடல் துணை.",
    searchPlaceholder: "கோவில் பெயர், தெய்வம், நகரம், மாநிலம் தேடுக...",
    detectLocation: "தற்போதைய இருப்பிடத்தை பயன்படுத்தவும் (GPS)",
    popularTemples: "பிரபலமான வழிபாட்டுத் தலங்கள்",
    upcomingFestivals: "வரவிருக்கும் திருவிழாக்கள்",
    liveDarshan: "நேரடி தரிசனம் / விர்ச்சுவல் டூர்",
    exploreAll: "அனைத்து கோவில்களையும் ஆராய்க",
    nearbyTemples: "GPS அடிப்படையிலான அருகில் உள்ள கோவில்கள்",
    darshanPlanner: "AI தரிசனத் திட்டமிடுபவர்",
    spiritualBot: "AI ஆன்மீக உதவியாளர்",
    annadanam: "அன்னதானம் & பிரசாதம் வழிகாட்டி",
    dailyTimeline: "தினசரி கோவில் கால அட்டவணை",
    reviews: "பக்தர்களின் வழிபாட்டு அனுபவங்கள்",
    nearbyServicesLabel: "அத்தியாவசிய அருகில் உள்ள சேவைகள்",
    weatherTitle: "நேரடி கோவில் வானிலை",
    crowdPrediction: "நேரடி பக்தர்கள் கூட்டம் கணிப்பு",
    dressCodeTitle: "கட்டாய உடை நெறிமுறை",
    facilitiesTitle: "கோவில் வசதிகள் பட்டியல்",
    historyTitle: "புராதன வரலாறு & பாரம்பரியம்",
    contactTitle: "அலுவலகத் தொடர்பு விவரங்கள்",
    openNow: "தற்போது திறந்துள்ளது",
    closed: "மூடப்பட்டுள்ளது",
    available: "அன்னதானம் கிடைக்கிறது",
    limited: "குறைவாக உள்ளது",
    lowCrowd: "குறைவான கூட்டம் (தரிசனத்திற்கு உகந்தது)",
    mediumCrowd: "சராசரி கூட்டம்",
    highCrowd: "அதிகப்படியான கூட்டம்",
    menDress: "ஆண்கள் ஆடை",
    womenDress: "பெண்கள் ஆடை",
    restrictedDress: "தடைசெய்யப்பட்ட ஆடைகள்",
    adminDashboard: "நிர்வாகி டாஷ்போர்டு",
    authButton: "பக்தர்கள் உள்நுழைவு / பதிவு",
    languageSwitcher: "மொழியை மாற்றுக",
    chatGreeting: "வணக்கம்! நான் உங்கள் AI ஆன்மீக உதவியாளர். கோவில் வரலாறுகள், நேரங்கள், பிரசாதங்கள் அல்லது போக்குவரத்து பற்றி எது வேண்டுமானாலும் கேளுங்கள்.",

    // Temple names & labels mapping
    "Tirumala Venkateswara Temple": "திருமலை வெங்கடேஸ்வரா கோவில்",
    "Kashi Vishwanath Temple": "காசி விஸ்வநாதர் கோவில்",
    "Kedarnath Temple": "கேதார்நாத் கோவில்",
    "Meenakshi Temple": "மீனாட்சி அம்மன் கோவில்",
    "Harmandir Sahib (Golden Temple)": "ஹர்மந்திர் சாஹிப் (பொற்கோவில்)",
    "Jagannath Temple Puri": "புரி ஜெகந்நாதர் கோவில்",
    "Lord Venkateswara (Balaji)": "ஸ்ரீ வெங்கடேஸ்வரா சுவாமி (பாலாஜி)",
    "Lord Shiva (Vishwanatha)": "ஸ்ரீ விஸ்வநாதர் (சிவன்)",
    "Lord Shiva (Sadashiva)": "சதாசிவன் (சிவன்)",
    "Goddess Meenakshi (Parvati) & Sundareswarar (Shiva)": "மீனாட்சி அம்மன் & சுந்தரேஸ்வரர்",
    "Guru Granth Sahib": "குரு கிரந்த் சாஹிப்",
    "Lord Jagannath, Balabhadra & Subhadra": "ஜெகந்நாதர், பாலபத்ரர் & சுபத்ரா",
    "Andhra Pradesh": "ஆந்திரப் பிரதேசம்",
    "Uttar Pradesh": "உத்தரப் பிரதேசம்",
    "Uttarakhand": "உத்தராகண்ட்",
    "Tamil Nadu": "தமிழ்நாடு",
    "Punjab": "பஞ்சாப்",
    "Odisha": "ஒடிசா",
    "Tirupati": "திருப்பதி",
    "Varanasi": "வாரணாசி",
    "Kedarnath Valley": "கேதார்நாத் பள்ளத்தாக்கு",
    "Madurai": "மதுரை",
    "Amritsar": "அமிர்தசரஸ்",
    "Puri": "புரி",
    "Filter by Deity:": "தெய்வத்தின் அடிப்படையில் வடிகட்டவும்:",
    "Filter by State:": "மாநிலத்தின் அடிப்படையில் வடிகட்டவும்:",
    "All Deities": "அனைத்து தெய்வங்களும்",
    "All States": "அனைத்து மாநிலங்களும்",
    "Deity:": "தெய்வம்:",
    "Wheelchair Accessible": "மாற்றுத்திறனாளிகள் அணுகல்",
    "Annadanam Available": "அன்னதானம் உள்ளது",
    "No Shrines Matching Filters": "வடிகட்டிகளுக்கு பொருந்தும் கோவில்கள் ஏதுமில்லை",
    "Please try modifying your keywords or select another deity focus.": "தயவுசெய்து உங்கள் தேடல் சொற்களை மாற்றவும் அல்லது வேறு தெய்வத்தை தேர்ந்தெடுக்கவும்.",
    "GPS Distance Uncalculated": "ஜிபிஎஸ் தூரம் கணக்கிடப்படவில்லை",
    "Details": "விவரங்கள்",
    "Trust Verified": "அறக்கட்டளை சரிபார்க்கப்பட்டது",
    "6 grand shrines logged": "6 பெரும் கோவில்கள் பதிவு செய்யப்பட்டுள்ளன",
    "🕉️ Sacred Devasthanam Aggregator": "🕉️ புனித தேவஸ்தானங்களின் தொகுப்பு",
    "Upcoming Religious Carnivals & Celebrations": "வரவிருக்கும் திருவிழாக்கள் & கொண்டாட்டங்கள்",

    // Descriptions
    "Perched atop the seven hills of Seshachalam, Tirumala Venkateswara Temple is the most visited, wealthiest, and spiritually radiant temple in the world. Revered as Kaliyuga Vaikuntam, this historical shrine represents pristine Dravidian architecture and eternal spiritual energy.": "சேஷாச்சலத்தின் ஏழு மலைகளின் மீது அமைந்துள்ள திருமலை வெங்கடேஸ்வரா கோவில், உலகின் அதிகப்படியான மக்கள் தரிசனம் செய்யும் மற்றும் ஆன்மீக ஒளி வீசும் தலமாகும்.",
    "Located on the sacred western bank of the holy Ganges river in Varanasi, Kashi Vishwanath contains the venerated Jyotirlinga, the golden spire of spiritual axis representing the cosmic light of Shiva. It represents liberation (Moksha) and timeless continuous prayers.": "வாரணாசில் புனித கங்கை நதியின் மேற்கு கரையில் அமைந்துள்ள காசி விஸ்வநாதர் கோவில், மோட்சம் மற்றும் ஆன்மீகத்தின் பிரதான மையமாக திகழ்கிறது.",
    "Nestled in the majestic snow-clad Garhwal Himalayas at 3,583 meters above sea level near Mandakini river, Kedarnath represents the highest of 12 Jyotirlingas, representing eternal absolute presence of Lord Shiva as Pandavas' divine redeemer.": "மந்தாகினி நதிக்கு அருகில் கடல் மட்டத்திலிருந்து 3,583 மீட்டர் உயரத்தில் பனிபடர்ந்த இமயமலையில் அமைந்துள்ள கேதார்நாத், 12 ஜோதிர்லிங்கங்களில் மிக உயர்ந்தது.",
    "Spanning 14 sprawling acres in the ancient heart of Madurai city, the Meenakshi Temple features 14 majestic multi-colored Gopurams decorated with thousands of concrete deities. It is the absolute epitome of complex classical visual architecture of Pandyan rulers.": "மதுரையின் மையப்பகுதியில் 14 ஏக்கர் பரப்பளவில் அமைந்துள்ள மீனாட்சி அம்மன் கோவில், ஆயிரக்கணக்கான சிலைகளால் அலங்கரிக்கப்பட்ட 14 கம்பீரமான கோபுரங்களை கொண்டது.",
    "Revered globally as the Harmandir Sahib, the Golden Temple is the pre-eminent spiritual pilgrimage site of Sikhism. Built around a beautiful holy pool (Amrit Sarovar), its absolute golden exterior stands as an architectural representation of cosmic peace, equality, and unceasing humanitarian support.": "புனித அமிர்த குளம் (அமிர்த சரோவர்) சுற்றி கட்டப்பட்டுள்ள பொற்கோவில் சீக்கிய மதத்தின் மிக முக்கியமான ஆன்மீக யாத்திரை தலமாகும்.",
    "Located on the divine eastern coast of Bay of Bengal, the sacred Jagannath Temple is a core Char Dham pilgrimage site representing spiritual royalty and mysterious celestial occurrences. It houses the wooden deities Lord Jagannath, Balabhadra, and Subhadra who are periodically replaced.": "வங்காள விரிகுடாவின் கிழக்கு கடற்கரையில் அமைந்துள்ள ஜெகந்நாதர் கோவில், புகழ்பெற்ற சார்தாம் திருத்தலங்களில் ஒன்றாகும். இங்கு மரத்தால் ஆன சிலைகள் வழிபடப்படுகின்றன."
  },
  kn: {
    discoverTemples: "ದೇವಾಲಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ • ದರ್ಶನ ಯೋಜಿಸಿ • ಆಧ್ಯಾತ್ಮಿಕತೆಯನ್ನು ಅನುಭವಿಸಿ",
    tagline: "ದರ್ಶನಗೈಡ್ — ನಿಮ್ಮ ಸಮಗ್ರ ಆಧ್ಯಾತ್ಮಿಕ ಯಾತ್ರಾ ಯೋಜನೆ ಮತ್ತು ಪರಿಶೋಧನೆಯ ಒಡನಾಡಿ.",
    searchPlaceholder: "ದೇವಾಲಯದ ಹೆಸರು, ದೇವತೆ, ನಗರ ಅಥವಾ ರಾಜ್ಯದ ಮೂಲಕ ಹುಡುಕಿ...",
    detectLocation: "ಪ್ರಸ್ತುತ ಜಿಪಿಎಸ್ ಸ್ಥಳ ಗುರುತಿಸಿ",
    popularTemples: "ಜನಪ್ರಿಯ ದೇವಾಲಯಗಳು",
    upcomingFestivals: "ಮುಂಬರುವ ಹಬ್ಬಗಳು",
    liveDarshan: "ಲೈವ್ ದರ್ಶನ / ವರ್ಚುವಲ್ ಪ್ರವಾಸ",
    exploreAll: "ಎಲ್ಲಾ ದೇವಾಲಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    nearbyTemples: "ಜಿಪಿಎಸ್ ಆಧಾರಿತ ಸಮೀಪದ ದೇವಾಲಯಗಳು",
    darshanPlanner: "AI ದರ್ಶನ ಯೋಜಕ",
    spiritualBot: "AI ಆಧ್ಯಾತ್ಮಿಕ ಸಹಾಯಕ",
    annadanam: "ಅನ್ನದಾನ ಮತ್ತು ಪ್ರಸಾದ ಮಾಹಿತಿ",
    dailyTimeline: "ದೈನಂದಿನ ವೇಳಾಪಟ್ಟಿ",
    reviews: "ಭಕ್ತರ ವಿಮರ್ಶೆಗಳು ಮತ್ತು ಅನುಭವಗಳು",
    nearbyServicesLabel: "ಅಗತ್ಯ ಸಮೀಪದ ಸೇವೆಗಳು",
    weatherTitle: "ಲೈವ್ ದೇವಾಲಯದ ವಾತಾವರಣ",
    crowdPrediction: "ಜನದಟ್ಟಣೆ ಮುನ್ಸೂಚನೆ",
    dressCodeTitle: "ಕಡ್ಡಾಯ ಉಡುಪು ನಿಯಮಗಳು",
    facilitiesTitle: "ದೇವಾಲಯದ ಸೌಲಭ್ಯಗಳ ಪಟ್ಟಿ",
    historyTitle: "ಪ್ರಾಚೀನ ಇತಿಹಾಸ ಮತ್ತು ಪರಂಪರೆ",
    contactTitle: "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    openNow: "ಈಗ ತೆರೆದಿದೆ",
    closed: "ಮುಚ್ಚಲಾಗಿದೆ",
    available: "ಲಭ್ಯವಿದೆ",
    limited: "ಸೀಮಿತ ಪ್ರಮಾಣ",
    lowCrowd: "ಕಡಿಮೆ ದಟ್ಟಣೆ (ದರ್ಶನಕ್ಕೆ ಸೂಕ್ತ ಸಮಯ)",
    mediumCrowd: "ಸಾಧಾರಣ ದಟ್ಟಣೆ",
    highCrowd: "ಅತಿಯಾದ ಜನದಟ್ಟಣೆ",
    menDress: "ಪುರುಷರ ಉಡುಪು",
    womenDress: "ಮಹಿಳೆಯರ ಉಡುಪು",
    restrictedDress: "ನಿಷೇಧಿತ ಉಡುಪುಗಳು",
    adminDashboard: "ಮ್ಯಾನೇಜ್ಮೆಂಟ್ ಡೆಸ್ಕ್",
    authButton: "ಭಕ್ತರ ಲಾಗಿನ್ / ಸೈನ್ ಅಪ್",
    languageSwitcher: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
    chatGreeting: "ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AI ಆಧ್ಯಾತ್ಮಿಕ ಮಾರ್ಗದರ್ಶಿ. ದೇವಾಲಯದ ಇತಿಹಾಸ, ಪೂಜಾ ಸಮಯಗಳು ಮತ್ತು ಅನ್ನದಾನದ ಬಗ್ಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ.",

    // Temple names & labels mapping
    "Tirumala Venkateswara Temple": "ತಿರುಮಲ ವೆಂಕಟೇಶ್ವರ ದೇವಾಲಯ",
    "Kashi Vishwanath Temple": "ಕಾಶಿ ವಿಶ್ವನಾಥ ದೇವಾಲಯ",
    "Kedarnath Temple": "ಕೇದಾರನಾಥ ದೇವಾಲಯ",
    "Meenakshi Temple": "ಮೀನಾಕ್ಷಿ ದೇವಾಲಯ",
    "Harmandir Sahib (Golden Temple)": "ಹರ್ಮಂತಿರ್ ಸಾಹಿಬ್ (ಚಿನ್ನದ ದೇವಸ್ಥಾನ)",
    "Jagannath Temple Puri": "ಪುರಿ ಜಗನ್ನಾಥ ದೇವಾಲಯ",
    "Lord Venkateswara (Balaji)": "ಶ್ರೀ ವೆಂಕಟೇಶ್ವರ ಸ್ವಾಮಿ (ಬಾಲಾಜಿ)",
    "Lord Shiva (Vishwanatha)": "ಶಿವ (ವಿಶ್ವನಾಥ)",
    "Lord Shiva (Sadashiva)": "ಶಿವ (ಸದಾಶಿವ)",
    "Goddess Meenakshi (Parvati) & Sundareswarar (Shiva)": "ಮೀನಾಕ್ಷಿ ದೇವಿ (ಪಾರ್ವತಿ) ಹಾಗೂ ಸುಂದರೇಶ್ವರ (ಶಿವ)",
    "Guru Granth Sahib": "ಗುರು ಗ್ರಂಥ್ ಸಾಹಿಬ್",
    "Lord Jagannath, Balabhadra & Subhadra": "ಜಗನ್ನಾಥ, ಬಲಭದ್ರ ಮತ್ತು ಸುಭದ್ರಾ",
    "Andhra Pradesh": "ಆಂಧ್ರ ಪ್ರದೇಶ",
    "Uttar Pradesh": "ಉತ್ತರ ಪ್ರದೇಶ",
    "Uttarakhand": "ಉತ್ತರಾಖಂಡ",
    "Tamil Nadu": "ತಮಿಳುನಾಡು",
    "Punjab": "ಪಂಜಾಬ್",
    "Odisha": "ಒಡಿಸ್ಸಾ",
    "Tirupati": "ತಿರುಪತಿ",
    "Varanasi": "ವಾರಣಾಸಿ",
    "Kedarnath Valley": "ಕೇದಾರನಾಥ ಕಣಿವೆ",
    "Madurai": "ಮಧುರೈ",
    "Amritsar": "ಅಮೃತಸರ",
    "Puri": "ಪ್ರಸಿ",
    "Filter by Deity:": "ದೇವತೆಯ ಆಧಾರದ ಮೇಲೆ ಫಿಲ್ಟರ್:",
    "Filter by State:": "ರಾಜ್ಯದ ಆಧಾರದ ಮೇಲೆ ಫಿಲ್ಟರ್:",
    "All Deities": "ಎಲ್ಲಾ ದೇವತೆಗಳು",
    "All States": "ಎಲ್ಲಾ ರಾಜ್ಯಗಳು",
    "Deity:": "ದೇವತೆ:",
    "Wheelchair Accessible": "ವೀಲಚೇರ್ ಲಭ್ಯವಿದೆ",
    "Annadanam Available": "ಅನ್ನದಾನ ಲಭ್ಯವಿದೆ",
    "No Shrines Matching Filters": "ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ದೇವಾಲಯಗಳಿಲ್ಲ",
    "Please try modifying your keywords or select another deity focus.": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕೀವರ್ಡ್ ಬದಲಾಯಿಸಲು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಬೇರೆ ದೇವತೆಯನ್ನು ಆಯ್ದುಕೊಳ್ಳಿ.",
    "GPS Distance Uncalculated": "ಜಿಪಿಎಸ್ ದೂರ ಲೆಕ್ಕಹಾಕಿಲ್ಲ",
    "Details": "ವಿವರಗಳು",
    "Trust Verified": "ಟ್ರಸ್ಟ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    "6 grand shrines logged": "6 ಪ್ರಮುಖ ಕ್ಷೇತ್ರಗಳು ದಾಖಲಾಗಿವೆ",
    "🕉️ Sacred Devasthanam Aggregator": "🕉️ ಪವಿತ್ರ ದೇವಸ್ಥಾನಗಳ ಸಂಗ್ರಹ",
    "Upcoming Religious Carnivals & Celebrations": "ಮುಂಬರುವ ಧಾರ್ಮಿಕ ಕಾರ್ನೀವಲ್ಗಳು ಮತ್ತು ಆಚರಣೆಗಳು",

    // Descriptions
    "Perched atop the seven hills of Seshachalam, Tirumala Venkateswara Temple is the most visited, wealthiest, and spiritually radiant temple in the world. Revered as Kaliyuga Vaikuntam, this historical shrine represents pristine Dravidian architecture and eternal spiritual energy.": "ಏಳು ಬೆಟ್ಟಗಳ ಮೇಲೆ ಸ್ಥಾಪಿತವಾದ ತಿರುಮಲ ವೆಂಕಟೇಶ್ವರ ದೇವಾಲಯ ವಿಶ್ವದ ಅತ್ಯಂತ ಪ್ರಸಿದ್ಧ ಹಾಗೂ ಶ್ರೀಮಂತ ಧಾರ್மಿಕ ಕೇಂದ್ರವಾಗಿದೆ.",
    "Located on the sacred western bank of the holy Ganges river in Varanasi, Kashi Vishwanath contains the venerated Jyotirlinga, the golden spire of spiritual axis representing the cosmic light of Shiva. It represents liberation (Moksha) and timeless continuous prayers.": "ವಾರಣಾಸಿಯ ಪವಿತ್ರ ಗಂಗಾನದಿಯ ದಂಡೆಯ ಮೇಲಿರುವ ಕಾಶಿ ವಿಶ್ವನಾಥ ದೇವಾಲಯವು ಜ್ಯೋತಿರ್ಲಿಂಗವನ್ನು ಒಳಗೊಂಡಿದ್ದು ಮೋಕ್ಷ ಜ್ಞಾನದ ಸಂಕೇತವಾಗಿದೆ.",
    "Nestled in the majestic snow-clad Garhwal Himalayas at 3,583 meters above sea level near Mandakini river, Kedarnath represents the highest of 12 Jyotirlingas, representing eternal absolute presence of Lord Shiva as Pandavas' divine redeemer.": "ಮಂದಾಕಿನಿ ನದಿಯ ಸಮೀಪ ಹಿಮಾಚ್ಛಾದಿತ ಗರ್ವಾಲ್ ಹಿಮಾಲಯ ಪರ್ವತ ಶ್ರೇಣಿಯಲ್ಲಿರುವ ಕೇದಾರನಾಥವು ಶಿವನ ಅತ್ಯುನ್ನತ ಜ್ಯೋತಿರ್ಲಿಂಗವಾಗಿದೆ.",
    "Spanning 14 sprawling acres in the ancient heart of Madurai city, the Meenakshi Temple features 14 majestic multi-colored Gopurams decorated with thousands of concrete deities. It is the absolute epitome of complex classical visual architecture of Pandyan rulers.": "ಮಧುರೈ ನಗರದ ಹೃದಯಭಾಗದಲ್ಲಿರುವ ಮೀನಾಕ್ಷಿ ದೇವಾಲಯವು ಭವ್ಯವಾದ ಬಣ್ಣಬಣ್ಣದ ಗೋಪುರಗಳನ್ನು ಹೊಂದಿರುವ ವೈಭವದ ವಾಸ್ತುಶಿಲ್ಪವಾಗಿದೆ.",
    "Revered globally as the Harmandir Sahib, the Golden Temple is the pre-eminent spiritual pilgrimage site of Sikhism. Built around a beautiful holy pool (Amrit Sarovar), its absolute golden exterior stands as an architectural representation of cosmic peace, equality, and unceasing humanitarian support.": "ಪವಿತ್ರ ಅಮೃತ ಸರೋವರದ ಮಧ್ಯೆ ಇರುವ ಈ ಚಿನ್ನದ ದೇವಾಲಯವು ಸಿಖ್ ಧರ್ಮದ ಪವಿತ್ರ ಯಾತ್ರಾಸ್ಥಳವಾಗಿದ್ದು ಶಾಂತಿಯ ಸಂಕೇತವಾಗಿದೆ.",
    "Located on the divine eastern coast of Bay of Bengal, the sacred Jagannath Temple is a core Char Dham pilgrimage site representing spiritual royalty and mysterious celestial occurrences. It houses the wooden deities Lord Jagannath, Balabhadra, and Subhadra who are periodically replaced.": "ಬಂಗಾಳ ಕೊಲ್ಲಿಯ ಸಮೀಪವಿರುವ ಜಗನ್ನಾಥ ದೇವಾಲಯವು ಸುಪ್ರಸಿದ್ಧ ಚಾರ್ ಧಾಮ್ ಯಾತ್ರಾ ಸ್ಥಳವಾಗಿದ್ದು ರಥಯಾತ್ರೆಗೆ ಅತ್ಯಂತ ಪ್ರಸಿದ್ಧಿಯಾಗಿದೆ."
  }
};
